### ISSUE TITLE
Create a documentation and test the project

### ISSUE THREAD

**Issue by piercus** [teamklap/term-annotator#1]
Please : 
* make this electron app run locally on your desktop.
* put all the steps in the README (for smita to be able to run it on her side)
* test it with the configuration i will send you

Once it will work, ask me for review

**Comment by TaniaPash** [comment]
> make this electron app run locally on your desktop.

done

> put all the steps in the README (for smita to be able to run it on her side)

1. Could you please give me access to this repo. so 'i'll create develop branch ? 
2. Please confirm my understanding: 
we will use this app to split video into segments and annotate each of theme with correct category 
so the main workflow will look like this:
- watch video
- split into pieces/segments (if was detected different categories in video)
- annotate each new segment or whole video. 

am i right ? 

3. Can i start work on docs in https://github.com/teamklap/term-annotator/wiki ? 
i want to add explicit info regarding installing repo and updating of config file. 

> test it with the configuration i will send you

Could you please share it with me ?

**Comment by piercus** [comment]
> Could you please give me access to this repo. so 'i'll create develop branch ?

Done

> am i right ?

Yes

> Can i start work on docs in https://github.com/teamklap/term-annotator/wiki ?

Please work on README.md

> test it with the configuration i will send you

Sent on slack

**Comment by TaniaPash** [comment]
@piercus 
could you please check these changes and give me a few advice on the improvement of instruction? 
https://github.com/teamklap/term-annotator/blob/develop/README.md

**Comment by TaniaPash** [comment]
done
