### ISSUE TITLE
Clean up/document import/export results format

### ISSUE THREAD

**Issue by piercus** [teamklap/term-annotator#21]
* Add documentation in the readme regarding import/export results format
  * export format
  * explanation of how to use it
* Change export format to not consider categories but only consider the folders like 

```
{
  "epoch": "2019-10-25T11:13:02.723Z",
  "folders": {
    "../annotated/1-5" : {
            "thumbnail": null,
            "filenames": [
              "a",
              "b",
              "c",
              "w"
            ]          
     },
     ...
    "../annotated/notClean":
      {
        "filenames": [
          "q",
          "p",
          "r",
          "s"
        ],
        "thumbnail": null,
        "dir": "not-clean"
      }  
   }
}
```
* Document term-annotaor input/outputs https://github.com/teamklap/term-annotator/blob/master/lib/export-results.js using jsdoc
* Document import-resulsts
* Document other function without jsdoc
* Create a node binary function `node bin/import-results.js --results data/example-results.js --source-folder tmp/src --destination-folder tmp/dest`
  * this function will use `lib/helpers/import-results.js` but not any electron component
  * another function `lib/backend/import-results.js' will do dialog/store and call `lib/helpers/import-results.js`
* Same exercise must be done regarding `node bin/export-results.js --destination-folder tmp/dest --results tmp/example-results.json`
* Everything erlated to app stuctures (config/results format ...) must be in `lib/helpers` and seperated to rtghe electron stuff in `lib/backend` and `lib/frontend`

Similar issue will be open in belley-annotation

**Comment by TaniaPash** [comment]
PR: https://github.com/teamklap/term-annotator/pull/24

**Comment by TaniaPash** [comment]
done
