### ISSUE TITLE
Urbansoccer: remove teams choice from config file

### ISSUE THREAD

**Issue by TaniaPash** [teamklap/term-annotator#22]
## Actual

User is annotating Players category with 3 steps: 
1. choose player
2. choose a team
3. choose a player

## Expected

1. User is annotation Players with only one step 
      - choose a player (press one key on a keyboard: 1,2,3,4,5.....)
2. A Thumbnail appears under each category

**Comment by TaniaPash** [comment]
hi @smitajha 

Could you please retest the new app version with a new config file? 

- app: https://drive.google.com/file/d/1ZfC0uRVzsIH7l547D7wJ6PXE4lSWImlb/view?usp=sharing

-  config file: https://drive.google.com/file/d/1CI9zqMcEeOBsSezXWHd_x7LP3AUos5V7/view?usp=sharing

- dataset: a dataset that was shared before: https://drive.google.com/open?id=1ygA3KS6IM5PR4hWJHmd5iDI1RMY9hJtg

The main goal of this test is to check if the app works well with a new config. 

Test workflow:
1. annotate ~30 images 
2. generate results
3. check if:
        - a thumbnail appear under each category
        - if gifs are sorted into "Annotated" folder
        - you are able to generate a result  (please share result file here also)
 

thank you for your help!

**Comment by smitajha** [comment]
@TaniaPash Please confirm that

### Expected

Annotator is choosing now player/mixed/notPlayer/notClean in one step 
![image](https://user-images.githubusercontent.com/16814737/68282705-24c6d800-00a0-11ea-94ba-e3e10eb1f337.png)

Thanks

**Comment by TaniaPash** [comment]
@smitajha i confirm

**Comment by TaniaPash** [comment]
hi @smitajha 

yes, 
could you please test and tell if it is comfortable to use `one-step-choice` or not.

Thank you!

**Comment by smitajha** [comment]
@TaniaPash  

There should be category from Player1 to Player10, 

Player1 to Player5 -- For red jersey  team and Player6 to Player9 ---For blue jersey team. Isn't it?

![image](https://user-images.githubusercontent.com/16814737/68295058-86df0780-00b7-11ea-822d-593dbd38decb.png)

Thanks,

**Comment by TaniaPash** [comment]
@smitajha 
you are right.

The config file was updated. 
please re-download it and test again.
thank you

**Comment by smitajha** [comment]
@TaniaPash 

I have tested this issue,

** File location** https://drive.google.com/drive/folders/1jqFyTmf_lQdIaftCbkC6uM_UYGsJj8Bd?usp=sharing

I have given you access already.

**Comment by TaniaPash** [comment]
done. 

teams choice was removed from a config file.
